import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { useRef, useEffect } from 'react';

import logo from '../assets/logo.png';

import Navbar from '../components/Navbar';

import styles from '../../styles/styles.module.css';

export default function Home() {

  // const mobileMenu = useRef();

  // useEffect(() => {

  //   function initiate(){

  //     class mobileMenu {
  //       constructor(mobileMenu, navList, navLinks) {
  //         this.mobileMenu = document.querySelector(mobileMenu);
  //         this.navList = document.querySelector(navList);
  //         this.navLinks = document.querySelectorAll(navLinks);
  //         this.activeClass = "active";
      
  //         this.handleClick = this.handleClick.bind(this);
  //       }
      
  //       animateLinks() {
  //         this.navLinks.forEach((link, index) => {
  //           link.style.animation
  //             ? (link.style.animation = "")
  //             : (link.style.animation = `navLinkFade 0.5s ease forwards ${
  //                 index / 7 + 0.3
  //               }s`);
  //         });
  //       }
      
  //       handleClick() {
  //         this.navList.classList.toggle(this.activeClass);
  //         this.mobileMenu.classList.toggle(this.activeClass);
  //         this.animateLinks();
  //       }
      
  //       addClickEvent() {
  //         this.mobileMenu.addEventListener("click", this.handleClick);
  //         console.log(this.handleClick)
  //       }
      
  //       init() {
  //         if (this.mobileMenu) {
  //           this.addClickEvent();
  //         }
  //         return this;
  //       }
  //     }
      
  //     const mobileNavbar = new mobileMenu(
  //       ".mobile-menu",
  //       ".nav-list",
  //       ".nav-list li",
  //     );
  //     mobileNavbar.init();

  //   }



  // }, [])


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
        
      <main className={styles.content}></main>
    </div>
  )
}
